language: python
python: 2.7
sudo: required
dist: trusty
before_install:
  - pwd
  - cd /tmp
  - git clone https://github.com/singularityware/singularity.git
  - cd singularity
  - ./autogen.sh
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
install:
  - pwd
  - cd /home/travis/build/hurwitzlab/muscope-18SV4
  - ls -l
  - make container
script:
  - pwd
  - ls -l
  - py.test tests/
notifications:
  email:
    on_success: never
    on_failure: always
