version: 2
jobs:
  build:
    docker:
      - image: python:2.7

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/muscope-18SV4

    branches:

    steps:
      - checkout

      - run:
          name: Install fastq-join.
          command: |
            export APP_DIR=/mu18SV4
            mkdir -p $APP_DIR
            cd $APP_DIR
            git clone https://github.com/brwnj/fastq-join
            cd fastq-join
            export FASTQ_JOIN_PATH=$APP_DIR/fastq-join
            make
            export PATH=$FASTQ_JOIN_PATH:$PATH
            echo "installed fastq-join"
            echo "  PATH=$PATH"

      - run:
          name: Install vsearch.
          command: |
            export APP_DIR=/mu18SV4
            mkdir -p $APP_DIR
            cd $APP_DIR
            wget https://github.com/torognes/vsearch/releases/download/v2.4.3/vsearch-2.4.3-linux-x86_64.tar.gz -O /tmp/vsearch.tar.gz
            tar xzf /tmp/vsearch.tar.gz
            rm /tmp/vsearch.tar.gz
            mv $APP_DIR/vsearch-2.4.3-linux-x86_64 $APP_DIR/vsearch
            export VSEARCH_PATH=$APP_DIR/vsearch/bin
            export PATH=$VSEARCH_PATH:$PATH
            echo "installed vsearch"
            echo "  PATH=$PATH"

      - run:
          name: Install PR2.
          command: |
            apt install zip
            export APP_DIR=/mu18SV4
            mkdir -p $APP_DIR
            export PR2_DIR=$APP_DIR/pr2
            mkdir $PR2_DIR
            cd $PR2_DIR
            wget https://ndownloader.figshare.com/files/7381369 -O pr2_gb203_version_4.5.zip
            unzip pr2_gb203_version_4.5.zip
            rm pr2_gb203_version_4.5.zip
            export PATH=$PR2_DIR:$PATH
            echo "installed PR2"
            echo "  PATH=$PATH"

      - run:
          name: Install the beautiful software.
          command: |
            pip install numpy
            pip install .[dev,test]

      - run:
          name: Test the beautiful software.
          command: |
            py.test test/
