version: 2
jobs:
  build:
    docker:
      - image: python:2.7

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/muscope-18SV4

    branches:
      only:
        - master
        - develop
        - /feature-.*/

    steps:
      - checkout

     - run:
        name: Install Python deps in a venv
        command: |
          pip install .
