version: 2
jobs:
  build:
    docker:
      - image: python:2.7

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/muscope-18SV4

    branches:

    steps:
      - checkout

      - run:
          name: Install singularity.
          command: |
            cd /tmp
            git clone https://github.com/singularityware/singularity.git
            cd singularity
            ./autogen.sh
            ./configure --prefix=/usr/local
            make
            make install

      - run:
          name: Install and test the beautiful software.
          command: |
            singularity create --size 2048 singularity/muscope-18SV4.img
            singularity bootstrap singularity/muscope-18SV4.img singularity/muscope-18SV4.def
